# Snakefile - snakefile for exercise 1 of workflow class.

rule plot_data:
	input: "HEADERS.txt", "CRND0103-2020-AK_Aleknagik_1_NNE.txt"
	output: "Rplot001.png"
	shell: "module load R; Rscript plot_files.r HEADERS.txt CRND0103-2020-AK_Aleknagik_1_NNE.txt"

rule download_data:
	output: "CRND0103-2020-AK_Aleknagik_1_NNE.txt"
	shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2020/CRND0103-2020-AK_Aleknagik_1_NNE.txt"

rule download_header:
	output: "HEADERS.txt"
	shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/HEADERS.txt"
